apiVersion: apps/v1
kind: {{ .Values.kind | default "Deployment" }}
metadata:
  name: {{ include "flamingo.fullname" . }}
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
spec:
  {{- if eq (.Values.kind | default "Deployment") "Deployment" }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flamingo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flamingo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flamingo.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork | default false }}
      dnsPolicy: {{ .Values.dnsPolicy | default "ClusterFirst" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.extraEnv .Values.config.secretOutputs .Values.config.existingOutputsSecret }}
          env:
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            {{- if .Values.config.protocols }}
            - "--protocols={{ .Values.config.protocols }}"
            {{- end }}
            {{- if .Values.config.verbose }}
            - "--verbose"
            {{- end }}
            {{- if .Values.config.quiet }}
            - "--quiet"
            {{- end }}
            {{- if .Values.config.dontIgnoreFailures }}
            - "--dont-ignore"
            {{- end }}
            {{- if .Values.config.ports.ftp }}
            - "--ftp-ports={{ .Values.config.ports.ftp }}"
            {{- end }}
            {{- if .Values.config.ports.imap }}
            - "--imap-ports={{ .Values.config.ports.imap }}"
            {{- end }}
            {{- if .Values.config.ports.imaps }}
            - "--imaps-ports={{ .Values.config.ports.imaps }}"
            {{- end }}
            {{- if .Values.config.ports.pop3 }}
            - "--pop3-ports={{ .Values.config.ports.pop3 }}"
            {{- end }}
            {{- if .Values.config.ports.pop3s }}
            - "--pop3s-ports={{ .Values.config.ports.pop3s }}"
            {{- end }}
            {{- if .Values.config.ports.smtp }}
            - "--smtp-ports={{ .Values.config.ports.smtp }}"
            {{- end }}
            {{- if .Values.config.ports.smtps }}
            - "--smtps-ports={{ .Values.config.ports.smtps }}"
            {{- end }}
            {{- if .Values.config.ports.redis }}
            - "--redis-ports={{ .Values.config.ports.redis }}"
            {{- end }}
            {{- if .Values.config.ports.telnet }}
            - "--telnet-ports={{ .Values.config.ports.telnet }}"
            {{- end }}
            {{- if .Values.config.ports.postgres }}
            - "--postgres-ports={{ .Values.config.ports.postgres }}"
            {{- end }}
            {{- if .Values.config.ports.mysql }}
            - "--mysql-ports={{ .Values.config.ports.mysql }}"
            {{- end }}
            {{- if .Values.config.banners.mysql }}
            - "--mysql-banner={{ .Values.config.banners.mysql }}"
            {{- end }}
            {{- if .Values.config.ports.mongodb }}
            - "--mongodb-ports={{ .Values.config.ports.mongodb }}"
            {{- end }}
            {{- if .Values.config.ports.smb }}
            - "--smb-ports={{ .Values.config.ports.smb }}"
            {{- end }}
            {{- if .Values.config.ports.winrm }}
            - "--winrm-ports={{ .Values.config.ports.winrm }}"
            {{- end }}
            {{- if .Values.config.ports.winrms }}
            - "--winrms-ports={{ .Values.config.ports.winrms }}"
            {{- end }}
            {{- if .Values.config.ports.kerberos }}
            - "--kerberos-ports={{ .Values.config.ports.kerberos }}"
            {{- end }}
            {{- if .Values.config.ports.docker }}
            - "--docker-ports={{ .Values.config.ports.docker }}"
            {{- end }}
            {{- if .Values.config.ports.dockertls }}
            - "--dockertls-ports={{ .Values.config.ports.dockertls }}"
            {{- end }}
            {{- if .Values.config.ports.kubelet }}
            - "--kubelet-ports={{ .Values.config.ports.kubelet }}"
            {{- end }}
            {{- if .Values.config.ports.etcd }}
            - "--etcd-ports={{ .Values.config.ports.etcd }}"
            {{- end }}
            {{- if .Values.config.ports.vnc }}
            - "--vnc-ports={{ .Values.config.ports.vnc }}"
            {{- end }}
            {{- if .Values.config.ports.mqtt }}
            - "--mqtt-ports={{ .Values.config.ports.mqtt }}"
            {{- end }}
            {{- if .Values.config.ports.mqtts }}
            - "--mqtts-ports={{ .Values.config.ports.mqtts }}"
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - "--metrics"
            - "--metrics-port={{ .Values.metrics.port }}"
            {{- end }}
            {{- if .Values.config.ports.dns }}
            - "--dns-ports={{ .Values.config.ports.dns }}"
            {{- end }}
            {{- if .Values.config.ports.dnsResolveToIP }}
            - "--dns-resolve-to={{ .Values.config.ports.dnsResolveToIP }}"
            {{- end }}
            {{- if .Values.config.ports.snmp }}
            - "--snmp-ports={{ .Values.config.ports.snmp }}"
            {{- end }}
            {{- if .Values.config.ports.ssh }}
            - "--ssh-ports={{ .Values.config.ports.ssh }}"
            {{- end }}
            {{- if .Values.config.sshHostKeySecret }}
            - "--ssh-host-key=/etc/flamingo/ssh/host_key"
            {{- end }}
            {{- if .Values.config.ports.ldap }}
            - "--ldap-ports={{ .Values.config.ports.ldap }}"
            {{- end }}
            {{- if .Values.config.ports.ldaps }}
            - "--ldaps-ports={{ .Values.config.ports.ldaps }}"
            {{- end }}
            {{- if .Values.config.ports.http }}
            - "--http-ports={{ .Values.config.ports.http }}"
            {{- end }}
            {{- if .Values.config.ports.https }}
            - "--https-ports={{ .Values.config.ports.https }}"
            {{- end }}
            {{- if .Values.config.httpRealm }}
            - "--http-realm={{ .Values.config.httpRealm }}"
            {{- end }}
            {{- if .Values.config.httpAuthMode }}
            - "--http-auth-mode={{ .Values.config.httpAuthMode }}"
            {{- end }}
            {{- if .Values.config.tlsName }}
            - "--tls-name={{ .Values.config.tlsName }}"
            {{- end }}
            {{- if .Values.config.tlsOrg }}
            - "--tls-org={{ .Values.config.tlsOrg }}"
            {{- end }}
            {{- if .Values.config.customTlsSecret }}
            - "--tls-cert=/etc/flamingo/tls/tls.crt"
            - "--tls-key=/etc/flamingo/tls/tls.key"
            {{- end }}
            {{- if .Values.enrichment.geoipCityDB }}
            - "--geoip-db={{ .Values.enrichment.geoipCityDB }}"
            {{- end }}
            {{- if .Values.enrichment.geoipAsnDB }}
            - "--asn-db={{ .Values.enrichment.geoipAsnDB }}"
            {{- end }}
            {{- if .Values.enrichment.enableRdns }}
            - "--enable-rdns"
            {{- end }}
            {{- if .Values.enrichment.torList }}
            - "--tor-list={{ .Values.enrichment.torList }}"
            {{- end }}
            {{- if .Values.enrichment.scannerList }}
            - "--scanner-list={{ .Values.enrichment.scannerList }}"
            {{- end }}
            {{- range .Values.config.outputs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            {{- if .Values.service.ports.ftp.enabled }}
            - name: ftp
              containerPort: {{ .Values.service.ports.ftp.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.imap.enabled }}
            - name: imap
              containerPort: {{ .Values.service.ports.imap.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.imaps.enabled }}
            - name: imaps
              containerPort: {{ .Values.service.ports.imaps.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.pop3.enabled }}
            - name: pop3
              containerPort: {{ .Values.service.ports.pop3.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.pop3s.enabled }}
            - name: pop3s
              containerPort: {{ .Values.service.ports.pop3s.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.smtp.enabled }}
            - name: smtp
              containerPort: {{ .Values.service.ports.smtp.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.smtps.enabled }}
            - name: smtps
              containerPort: {{ .Values.service.ports.smtps.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.redis.enabled }}
            - name: redis
              containerPort: {{ .Values.service.ports.redis.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.telnet.enabled }}
            - name: telnet
              containerPort: {{ .Values.service.ports.telnet.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.postgres.enabled }}
            - name: postgres
              containerPort: {{ .Values.service.ports.postgres.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.mysql.enabled }}
            - name: mysql
              containerPort: {{ .Values.service.ports.mysql.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.mongodb.enabled }}
            - name: mongodb
              containerPort: {{ .Values.service.ports.mongodb.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.smb.enabled }}
            - name: smb
              containerPort: {{ .Values.service.ports.smb.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.winrm.enabled }}
            - name: winrm
              containerPort: {{ .Values.service.ports.winrm.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.winrms.enabled }}
            - name: winrms
              containerPort: {{ .Values.service.ports.winrms.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.kerberosTcp.enabled }}
            - name: kerberos-tcp
              containerPort: {{ .Values.service.ports.kerberosTcp.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.kerberosUdp.enabled }}
            - name: kerberos-udp
              containerPort: {{ .Values.service.ports.kerberosUdp.targetPort }}
              protocol: UDP
            {{- end }}
            {{- if .Values.service.ports.docker.enabled }}
            - name: docker
              containerPort: {{ .Values.service.ports.docker.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.dockertls.enabled }}
            - name: dockertls
              containerPort: {{ .Values.service.ports.dockertls.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.kubelet.enabled }}
            - name: kubelet
              containerPort: {{ .Values.service.ports.kubelet.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.etcd.enabled }}
            - name: etcd
              containerPort: {{ .Values.service.ports.etcd.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.vnc.enabled }}
            - name: vnc
              containerPort: {{ .Values.service.ports.vnc.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.mqtt.enabled }}
            - name: mqtt
              containerPort: {{ .Values.service.ports.mqtt.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.mqtts.enabled }}
            - name: mqtts
              containerPort: {{ .Values.service.ports.mqtts.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.ssh.enabled }}
            - name: ssh
              containerPort: {{ .Values.service.ports.ssh.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.dnsTcp.enabled }}
            - name: dns-tcp
              containerPort: {{ .Values.service.ports.dnsTcp.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.dnsUdp.enabled }}
            - name: dns-udp
              containerPort: {{ .Values.service.ports.dnsUdp.targetPort }}
              protocol: UDP
            {{- end }}
            {{- if .Values.service.ports.http.enabled }}
            - name: http
              containerPort: {{ .Values.service.ports.http.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.snmp.enabled }}
            - name: snmp
              containerPort: {{ .Values.service.ports.snmp.targetPort }}
              protocol: UDP
            {{- end }}
            {{- if .Values.service.ports.ldap.enabled }}
            - name: ldap
              containerPort: {{ .Values.service.ports.ldap.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.https.enabled }}
            - name: https
              containerPort: {{ .Values.service.ports.https.targetPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.ldaps.enabled }}
            - name: ldaps
              containerPort: {{ .Values.service.ports.ldaps.targetPort }}
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.config.customTlsSecret }}
            - name: tls
              mountPath: /etc/flamingo/tls
              readOnly: true
            {{- end }}
            {{- if .Values.config.sshHostKeySecret }}
            - name: ssh-key
              mountPath: /etc/flamingo/ssh
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "flamingo.fullname" . }}
        {{- end }}
        {{- if .Values.config.customTlsSecret }}
        - name: tls
          secret:
            secretName: {{ .Values.config.customTlsSecret }}
        {{- end }}
        {{- if .Values.config.sshHostKeySecret }}
        - name: ssh-key
          secret:
            secretName: {{ .Values.config.sshHostKeySecret }}
            items:
              - key: id_rsa
                path: host_key
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
