{{- if .Values.config.secretOutputs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flamingo.fullname" . }}-outputs
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $i, $val := .Values.config.secretOutputs }}
  output-{{ $i }}: {{ $val | quote }}
  {{- end }}
{{- end }}
