{{- if not .Values.service.splitProtocols -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flamingo.fullname" . }}
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flamingo.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.ports.ftp.enabled }}
    - port: {{ .Values.service.ports.ftp.port }}
      targetPort: {{ .Values.service.ports.ftp.targetPort }}
      protocol: {{ .Values.service.ports.ftp.protocol | default "TCP" }}
      name: ftp
    {{- end }}
    {{- if .Values.service.ports.imap.enabled }}
    - port: {{ .Values.service.ports.imap.port }}
      targetPort: {{ .Values.service.ports.imap.targetPort }}
      protocol: {{ .Values.service.ports.imap.protocol | default "TCP" }}
      name: imap
    {{- end }}
    {{- if .Values.service.ports.imaps.enabled }}
    - port: {{ .Values.service.ports.imaps.port }}
      targetPort: {{ .Values.service.ports.imaps.targetPort }}
      protocol: {{ .Values.service.ports.imaps.protocol | default "TCP" }}
      name: imaps
    {{- end }}
    {{- if .Values.service.ports.pop3.enabled }}
    - port: {{ .Values.service.ports.pop3.port }}
      targetPort: {{ .Values.service.ports.pop3.targetPort }}
      protocol: {{ .Values.service.ports.pop3.protocol | default "TCP" }}
      name: pop3
    {{- end }}
    {{- if .Values.service.ports.pop3s.enabled }}
    - port: {{ .Values.service.ports.pop3s.port }}
      targetPort: {{ .Values.service.ports.pop3s.targetPort }}
      protocol: {{ .Values.service.ports.pop3s.protocol | default "TCP" }}
      name: pop3s
    {{- end }}
    {{- if .Values.service.ports.smtp.enabled }}
    - port: {{ .Values.service.ports.smtp.port }}
      targetPort: {{ .Values.service.ports.smtp.targetPort }}
      protocol: {{ .Values.service.ports.smtp.protocol | default "TCP" }}
      name: smtp
    {{- end }}
    {{- if .Values.service.ports.smtpSubmission.enabled }}
    - port: {{ .Values.service.ports.smtpSubmission.port }}
      targetPort: {{ .Values.service.ports.smtpSubmission.targetPort }}
      protocol: {{ .Values.service.ports.smtpSubmission.protocol | default "TCP" }}
      name: smtp-submission
    {{- end }}
    {{- if .Values.service.ports.smtps.enabled }}
    - port: {{ .Values.service.ports.smtps.port }}
      targetPort: {{ .Values.service.ports.smtps.targetPort }}
      protocol: {{ .Values.service.ports.smtps.protocol | default "TCP" }}
      name: smtps
    {{- end }}
    {{- if .Values.service.ports.redis.enabled }}
    - port: {{ .Values.service.ports.redis.port }}
      targetPort: {{ .Values.service.ports.redis.targetPort }}
      protocol: {{ .Values.service.ports.redis.protocol | default "TCP" }}
      name: redis
    {{- end }}
    {{- if .Values.service.ports.telnet.enabled }}
    - port: {{ .Values.service.ports.telnet.port }}
      targetPort: {{ .Values.service.ports.telnet.targetPort }}
      protocol: {{ .Values.service.ports.telnet.protocol | default "TCP" }}
      name: telnet
    {{- end }}
    {{- if .Values.service.ports.postgres.enabled }}
    - port: {{ .Values.service.ports.postgres.port }}
      targetPort: {{ .Values.service.ports.postgres.targetPort }}
      protocol: {{ .Values.service.ports.postgres.protocol | default "TCP" }}
      name: postgres
    {{- end }}
    {{- if .Values.service.ports.mysql.enabled }}
    - port: {{ .Values.service.ports.mysql.port }}
      targetPort: {{ .Values.service.ports.mysql.targetPort }}
      protocol: {{ .Values.service.ports.mysql.protocol | default "TCP" }}
      name: mysql
    {{- end }}
    {{- if .Values.service.ports.mongodb.enabled }}
    - port: {{ .Values.service.ports.mongodb.port }}
      targetPort: {{ .Values.service.ports.mongodb.targetPort }}
      protocol: {{ .Values.service.ports.mongodb.protocol | default "TCP" }}
      name: mongodb
    {{- end }}
    {{- if .Values.service.ports.smb.enabled }}
    - port: {{ .Values.service.ports.smb.port }}
      targetPort: {{ .Values.service.ports.smb.targetPort }}
      protocol: {{ .Values.service.ports.smb.protocol | default "TCP" }}
      name: smb
    {{- end }}
    {{- if .Values.service.ports.winrm.enabled }}
    - port: {{ .Values.service.ports.winrm.port }}
      targetPort: {{ .Values.service.ports.winrm.targetPort }}
      protocol: {{ .Values.service.ports.winrm.protocol | default "TCP" }}
      name: winrm
    {{- end }}
    {{- if .Values.service.ports.winrms.enabled }}
    - port: {{ .Values.service.ports.winrms.port }}
      targetPort: {{ .Values.service.ports.winrms.targetPort }}
      protocol: {{ .Values.service.ports.winrms.protocol | default "TCP" }}
      name: winrms
    {{- end }}
    {{- if .Values.service.ports.kerberosTcp.enabled }}
    - port: {{ .Values.service.ports.kerberosTcp.port }}
      targetPort: {{ .Values.service.ports.kerberosTcp.targetPort }}
      protocol: {{ .Values.service.ports.kerberosTcp.protocol | default "TCP" }}
      name: kerberos-tcp
    {{- end }}
    {{- if .Values.service.ports.kerberosUdp.enabled }}
    - port: {{ .Values.service.ports.kerberosUdp.port }}
      targetPort: {{ .Values.service.ports.kerberosUdp.targetPort }}
      protocol: {{ .Values.service.ports.kerberosUdp.protocol | default "UDP" }}
      name: kerberos-udp
    {{- end }}
    {{- if .Values.service.ports.docker.enabled }}
    - port: {{ .Values.service.ports.docker.port }}
      targetPort: {{ .Values.service.ports.docker.targetPort }}
      protocol: {{ .Values.service.ports.docker.protocol | default "TCP" }}
      name: docker
    {{- end }}
    {{- if .Values.service.ports.dockertls.enabled }}
    - port: {{ .Values.service.ports.dockertls.port }}
      targetPort: {{ .Values.service.ports.dockertls.targetPort }}
      protocol: {{ .Values.service.ports.dockertls.protocol | default "TCP" }}
      name: dockertls
    {{- end }}
    {{- if .Values.service.ports.kubelet.enabled }}
    - port: {{ .Values.service.ports.kubelet.port }}
      targetPort: {{ .Values.service.ports.kubelet.targetPort }}
      protocol: {{ .Values.service.ports.kubelet.protocol | default "TCP" }}
      name: kubelet
    {{- end }}
    {{- if .Values.service.ports.etcd.enabled }}
    - port: {{ .Values.service.ports.etcd.port }}
      targetPort: {{ .Values.service.ports.etcd.targetPort }}
      protocol: {{ .Values.service.ports.etcd.protocol | default "TCP" }}
      name: etcd
    {{- end }}
    {{- if .Values.service.ports.vnc.enabled }}
    - port: {{ .Values.service.ports.vnc.port }}
      targetPort: {{ .Values.service.ports.vnc.targetPort }}
      protocol: {{ .Values.service.ports.vnc.protocol | default "TCP" }}
      name: vnc
    {{- end }}
    {{- if .Values.service.ports.mqtt.enabled }}
    - port: {{ .Values.service.ports.mqtt.port }}
      targetPort: {{ .Values.service.ports.mqtt.targetPort }}
      protocol: {{ .Values.service.ports.mqtt.protocol | default "TCP" }}
      name: mqtt
    {{- end }}
    {{- if .Values.service.ports.mqtts.enabled }}
    - port: {{ .Values.service.ports.mqtts.port }}
      targetPort: {{ .Values.service.ports.mqtts.targetPort }}
      protocol: {{ .Values.service.ports.mqtts.protocol | default "TCP" }}
      name: mqtts
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.service.ports.ssh.enabled }}
    - port: {{ .Values.service.ports.ssh.port }}
      targetPort: {{ .Values.service.ports.ssh.targetPort }}
      protocol: {{ .Values.service.ports.ssh.protocol | default "TCP" }}
      name: ssh
    {{- end }}
    {{- if .Values.service.ports.dnsTcp.enabled }}
    - port: {{ .Values.service.ports.dnsTcp.port }}
      targetPort: {{ .Values.service.ports.dnsTcp.targetPort }}
      protocol: {{ .Values.service.ports.dnsTcp.protocol | default "TCP" }}
      name: dns-tcp
    {{- end }}
    {{- if .Values.service.ports.dnsUdp.enabled }}
    - port: {{ .Values.service.ports.dnsUdp.port }}
      targetPort: {{ .Values.service.ports.dnsUdp.targetPort }}
      protocol: {{ .Values.service.ports.dnsUdp.protocol | default "UDP" }}
      name: dns-udp
    {{- end }}
    {{- if .Values.service.ports.http.enabled }}
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol | default "TCP" }}
      name: http
    {{- end }}
    {{- if .Values.service.ports.snmp.enabled }}
    - port: {{ .Values.service.ports.snmp.port }}
      targetPort: {{ .Values.service.ports.snmp.targetPort }}
      protocol: {{ .Values.service.ports.snmp.protocol | default "UDP" }}
      name: snmp
    {{- end }}
    {{- if .Values.service.ports.ldap.enabled }}
    - port: {{ .Values.service.ports.ldap.port }}
      targetPort: {{ .Values.service.ports.ldap.targetPort }}
      protocol: {{ .Values.service.ports.ldap.protocol | default "TCP" }}
      name: ldap
    {{- end }}
    {{- if .Values.service.ports.https.enabled }}
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: {{ .Values.service.ports.https.protocol | default "TCP" }}
      name: https
    {{- end }}
    {{- if .Values.service.ports.ldaps.enabled }}
    - port: {{ .Values.service.ports.ldaps.port }}
      targetPort: {{ .Values.service.ports.ldaps.targetPort }}
      protocol: {{ .Values.service.ports.ldaps.protocol | default "TCP" }}
      name: ldaps
    {{- end }}
{{- else -}}
# TCP Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flamingo.fullname" . }}-tcp
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.tcpAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flamingo.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.ports.ftp.enabled }}
    - port: {{ .Values.service.ports.ftp.port }}
      targetPort: {{ .Values.service.ports.ftp.targetPort }}
      protocol: TCP
      name: ftp
    {{- end }}
    {{- if .Values.service.ports.imap.enabled }}
    - port: {{ .Values.service.ports.imap.port }}
      targetPort: {{ .Values.service.ports.imap.targetPort }}
      protocol: TCP
      name: imap
    {{- end }}
    {{- if .Values.service.ports.imaps.enabled }}
    - port: {{ .Values.service.ports.imaps.port }}
      targetPort: {{ .Values.service.ports.imaps.targetPort }}
      protocol: TCP
      name: imaps
    {{- end }}
    {{- if .Values.service.ports.pop3.enabled }}
    - port: {{ .Values.service.ports.pop3.port }}
      targetPort: {{ .Values.service.ports.pop3.targetPort }}
      protocol: TCP
      name: pop3
    {{- end }}
    {{- if .Values.service.ports.pop3s.enabled }}
    - port: {{ .Values.service.ports.pop3s.port }}
      targetPort: {{ .Values.service.ports.pop3s.targetPort }}
      protocol: TCP
      name: pop3s
    {{- end }}
    {{- if .Values.service.ports.smtp.enabled }}
    - port: {{ .Values.service.ports.smtp.port }}
      targetPort: {{ .Values.service.ports.smtp.targetPort }}
      protocol: TCP
      name: smtp
    {{- end }}
    {{- if .Values.service.ports.smtpSubmission.enabled }}
    - port: {{ .Values.service.ports.smtpSubmission.port }}
      targetPort: {{ .Values.service.ports.smtpSubmission.targetPort }}
      protocol: TCP
      name: smtp-submission
    {{- end }}
    {{- if .Values.service.ports.smtps.enabled }}
    - port: {{ .Values.service.ports.smtps.port }}
      targetPort: {{ .Values.service.ports.smtps.targetPort }}
      protocol: TCP
      name: smtps
    {{- end }}
    {{- if .Values.service.ports.redis.enabled }}
    - port: {{ .Values.service.ports.redis.port }}
      targetPort: {{ .Values.service.ports.redis.targetPort }}
      protocol: TCP
      name: redis
    {{- end }}
    {{- if .Values.service.ports.telnet.enabled }}
    - port: {{ .Values.service.ports.telnet.port }}
      targetPort: {{ .Values.service.ports.telnet.targetPort }}
      protocol: TCP
      name: telnet
    {{- end }}
    {{- if .Values.service.ports.postgres.enabled }}
    - port: {{ .Values.service.ports.postgres.port }}
      targetPort: {{ .Values.service.ports.postgres.targetPort }}
      protocol: TCP
      name: postgres
    {{- end }}
    {{- if .Values.service.ports.mysql.enabled }}
    - port: {{ .Values.service.ports.mysql.port }}
      targetPort: {{ .Values.service.ports.mysql.targetPort }}
      protocol: TCP
      name: mysql
    {{- end }}
    {{- if .Values.service.ports.mongodb.enabled }}
    - port: {{ .Values.service.ports.mongodb.port }}
      targetPort: {{ .Values.service.ports.mongodb.targetPort }}
      protocol: TCP
      name: mongodb
    {{- end }}
    {{- if .Values.service.ports.smb.enabled }}
    - port: {{ .Values.service.ports.smb.port }}
      targetPort: {{ .Values.service.ports.smb.targetPort }}
      protocol: TCP
      name: smb
    {{- end }}
    {{- if .Values.service.ports.winrm.enabled }}
    - port: {{ .Values.service.ports.winrm.port }}
      targetPort: {{ .Values.service.ports.winrm.targetPort }}
      protocol: TCP
      name: winrm
    {{- end }}
    {{- if .Values.service.ports.winrms.enabled }}
    - port: {{ .Values.service.ports.winrms.port }}
      targetPort: {{ .Values.service.ports.winrms.targetPort }}
      protocol: TCP
      name: winrms
    {{- end }}
    {{- if .Values.service.ports.kerberosTcp.enabled }}
    - port: {{ .Values.service.ports.kerberosTcp.port }}
      targetPort: {{ .Values.service.ports.kerberosTcp.targetPort }}
      protocol: TCP
      name: kerberos-tcp
    {{- end }}
    {{- if .Values.service.ports.docker.enabled }}
    - port: {{ .Values.service.ports.docker.port }}
      targetPort: {{ .Values.service.ports.docker.targetPort }}
      protocol: TCP
      name: docker
    {{- end }}
    {{- if .Values.service.ports.dockertls.enabled }}
    - port: {{ .Values.service.ports.dockertls.port }}
      targetPort: {{ .Values.service.ports.dockertls.targetPort }}
      protocol: TCP
      name: dockertls
    {{- end }}
    {{- if .Values.service.ports.kubelet.enabled }}
    - port: {{ .Values.service.ports.kubelet.port }}
      targetPort: {{ .Values.service.ports.kubelet.targetPort }}
      protocol: TCP
      name: kubelet
    {{- end }}
    {{- if .Values.service.ports.etcd.enabled }}
    - port: {{ .Values.service.ports.etcd.port }}
      targetPort: {{ .Values.service.ports.etcd.targetPort }}
      protocol: TCP
      name: etcd
    {{- end }}
    {{- if .Values.service.ports.vnc.enabled }}
    - port: {{ .Values.service.ports.vnc.port }}
      targetPort: {{ .Values.service.ports.vnc.targetPort }}
      protocol: TCP
      name: vnc
    {{- end }}
    {{- if .Values.service.ports.mqtt.enabled }}
    - port: {{ .Values.service.ports.mqtt.port }}
      targetPort: {{ .Values.service.ports.mqtt.targetPort }}
      protocol: TCP
      name: mqtt
    {{- end }}
    {{- if .Values.service.ports.mqtts.enabled }}
    - port: {{ .Values.service.ports.mqtts.port }}
      targetPort: {{ .Values.service.ports.mqtts.targetPort }}
      protocol: TCP
      name: mqtts
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.service.ports.ssh.enabled }}
    - port: {{ .Values.service.ports.ssh.port }}
      targetPort: {{ .Values.service.ports.ssh.targetPort }}
      protocol: TCP
      name: ssh
    {{- end }}
    {{- if .Values.service.ports.dnsTcp.enabled }}
    - port: {{ .Values.service.ports.dnsTcp.port }}
      targetPort: {{ .Values.service.ports.dnsTcp.targetPort }}
      protocol: TCP
      name: dns-tcp
    {{- end }}
    {{- if .Values.service.ports.http.enabled }}
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.service.ports.ldap.enabled }}
    - port: {{ .Values.service.ports.ldap.port }}
      targetPort: {{ .Values.service.ports.ldap.targetPort }}
      protocol: TCP
      name: ldap
    {{- end }}
    {{- if .Values.service.ports.https.enabled }}
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: TCP
      name: https
    {{- end }}
    {{- if .Values.service.ports.ldaps.enabled }}
    - port: {{ .Values.service.ports.ldaps.port }}
      targetPort: {{ .Values.service.ports.ldaps.targetPort }}
      protocol: TCP
      name: ldaps
    {{- end }}
---
# UDP Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flamingo.fullname" . }}-udp
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.udpAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flamingo.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.ports.dnsUdp.enabled }}
    - port: {{ .Values.service.ports.dnsUdp.port }}
      targetPort: {{ .Values.service.ports.dnsUdp.targetPort }}
      protocol: UDP
      name: dns-udp
    {{- end }}
    {{- if .Values.service.ports.snmp.enabled }}
    - port: {{ .Values.service.ports.snmp.port }}
      targetPort: {{ .Values.service.ports.snmp.targetPort }}
      protocol: UDP
      name: snmp
    {{- end }}
    {{- if .Values.service.ports.kerberosUdp.enabled }}
    - port: {{ .Values.service.ports.kerberosUdp.port }}
      targetPort: {{ .Values.service.ports.kerberosUdp.targetPort }}
      protocol: UDP
      name: kerberos-udp
    {{- end }}
{{- end }}
